### ISSUE TITLE
WAIL vs WAIL-Electron on Linux

### ISSUE THREAD

**Issue by zanoo** [machawk1/wail#472]
Is WAIL-Electron as feature-complete as WAIL? I'm on Linux, and trying to decide which one to use to archive a website. I noticed that commits to WAIL-Electron kind of stopped in 2017, so I wasn't sure if it was still getting updates and bugfixes. Does anyone have a short list of pros and cons, or just some insight, that might help me decide? Apologies if this is not the right venue to raise this question (and of course please close this issue if that's the case).

**Comment by machawk1** [comment]
Hi @zanoo,
WAIL-Electron took a different approach at web archiving using more contemporary tools for higher fidelity captures. WAIL "Classic", this very repo, never really had a stable version release for Linux, partially due to packaging complications but mostly attributed to lack of familiarity with GUI application conventions.

I know that WAIL-Electron is lagging a bit with its version of pywb (the replay software) due to an overhaul of the dependency. WAIL-Electron's development was mostly driven by @N0taN3rd as part of his MS degree work (I _was_ a PhD student then) but he has since graduated and I am unsure if he still has interest/time to develop and maintain it (feel free to correct me, John).

You might look to the [short paper](https://matkelly.com/papers/2017_jcdl_wail.pdf) that originally disseminated info about WAIL-Electron but it is brief and is not really a side-by-side feature comparison.

The crux is the tool set included. At the fundamental level, WAIL includes OpenWayback and Heritrix. WAIL-Electron substitutes OpenWayback for pywb and also bundles [node-warc](https://github.com/N0taN3rd/node-warc) and some additional capture tools to leverage headless browsers' features for preservation. 

This is certainly the correct medium to raise these questions, as I am actively monitoring the repo as well as maintaining and progressing the software as I find time, which is scarce. Contributions always welcome but additionally, your continued interest through submitting comments and issues ensures there is still a need and motivates "one" to continue development.

**Comment by zanoo** [comment]
Thank you very much for the prompt and informative response @machawk1! You completely answered all of my questions. I think WAIL-Electron is much more suitable for my purposes, so I'll download and use that. I'm glad that it's still functional! Reading that short paper also illuminated the functionality for me quite well--thanks for the tip! I'm glad I can motivate further development :)
