### ISSUE TITLE
Homepage download link doesn't do anything

### ISSUE THREAD

**Issue by maphew** [machawk1/wail#488]
Following https://machawk1.github.io/wail/#download (from https://machawk1.github.io/wail/) has no apparent effect.

**Comment by machawk1** [comment]
@maphew The "Download" links on that page bring the viewport to ensure the "Download" section is visible. Because this section is near the bottom of the page, the browser appears to "bottom out". I understand this might be visually confusing. Adding some whitespace to the bottom or perhaps highlighting the section following a click might remedy this UX issue.

Thanks for the feedback.

**Comment by machawk1** [comment]
@maphew I have updated the web page to make this effect more apparent.
